# Generated by Django 5.2.5 on 2025-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_user_user_mobile_alter_user_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/driving_license/'),
        ),
        migrations.AddField(
            model_name='user',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan_card/'),
        ),
        migrations.AddField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rc_book',
            field=models.FileField(blank=True, null=True, upload_to='documents/rc_book/'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
