# Generated by Django 5.2.5 on 2025-09-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='booking_id',
        ),
    ]
