# Generated by Django 5.2.5 on 2025-10-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancereward',
            name='vehicle_image',
            field=models.ImageField(blank=True, help_text='Upload vehicle image', null=True, upload_to='vehicle_images/'),
        ),
    ]
