# Generated by Django 5.2.5 on 2025-08-12 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_aadhaar_user_driving_license_user_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
