# Generated by Django 5.2.5 on 2025-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ride_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
