# Generated by Django 5.2.5 on 2025-10-28 07:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_distancereward_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallettransaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='adminwallettransaction',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
