# Generated by Django 5.2.5 on 2025-10-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adminwallettransaction_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancereward',
            name='heading',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='distancereward',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
