# Generated by Django 5.2.5 on 2025-10-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_distancereward_heading_distancereward_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('auto_cancelled', 'Auto Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userwallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('cashback', 'Cashback'), ('reward', 'Reward'), ('ride_payment', 'Ride Payment Debited'), ('refund', 'Refund Credited'), ('driver_incentive', 'Driver Incentive')], max_length=20),
        ),
    ]
