# Generated by Django 5.2.5 on 2025-10-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
