# Generated by Django 5.2.5 on 2025-10-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ride_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_amount', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('free_cancellations', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='cancellation_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_cancelled_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='pending_cancellation_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arrived', 'Arrived'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('auto_cancelled', 'Auto Cancelled'), ('cancelled_by_user', 'Cancelled by User')], default='pending', max_length=20),
        ),
    ]
