# Generated by Django 5.2.5 on 2025-10-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cancellationpolicy_ride_cancellation_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='free_cancellations',
            field=models.IntegerField(default=0),
        ),
    ]
