# Generated by Django 5.2.5 on 2025-11-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cancellationpolicy_free_cancellations'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverincentive',
            name='max_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverincentive',
            name='rides_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
