# Generated by Django 5.2.5 on 2025-11-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_driverincentive_max_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
